### ISSUE TITLE
New MQTT Definition in HA 2022.6

### ISSUE THREAD

**Issue by rugosch** [mfdlr/homeassistant-wlanthermo#4]
As mentioned in https://www.home-assistant.io/blog/2022/06/01/release-20226/#breaking-changes the old definition gets depreciated in 2022.9

Chan you please update you code?
Can't get the template sensors to work.

Thanks

**Comment by tempo3** [comment]
try this ;-)
mqtt:
  sensor:
    - name: "WLANThermo"
      state_topic: "WLanThermo/WLANThermo/status/data"
      value_template: "{{ value_json.system.soc }}"
      json_attributes_topic: "WLanThermo/WLANThermo/status/data"
      json_attributes_template: "{{ value_json | tojson }}"
      expire_after: 60

... and the  state_topic path must be yours

**Comment by rugosch** [comment]
This part I got right :)

But afterwards it won't accept the template sensors syntax anymore.

**Comment by tempo3** [comment]
Dont understand the question. Do you mean in the automations?

**Comment by rugosch** [comment]
I adapted the same way you did, so far so good

But then It is the part afterwards that is killing me, in the line
- platform: template

I think because auf removing "sensor" as the initial section identifier the whole template sensors afterwards are not working.

I get this error messag
<img width="910" alt="Editor" src="https://user-images.githubusercontent.com/85888606/175576165-0781719c-d680-4160-829a-9066f316d09e.png">
e

**Comment by tempo3** [comment]
there was a change in the method for the “sensor platform template” to “template sensor ” in 2021. I guess you must migrate your section to the new method. https://www.home-assistant.io/integrations/template/#legacy-binary-sensor-configuration-format
